# Generated by Django 3.2 on 2022-01-06 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_images/imtiyaz.jpeg', null=True, upload_to='profile_images/')),
                ('intro', models.TextField(blank=True, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(max_length=15)),
                ('twitter_ac', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_ac', models.CharField(blank=True, max_length=100, null=True)),
                ('gitHub_ac', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_ac', models.CharField(blank=True, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
