# Generated by Django 3.2 on 2022-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_workexpirnce_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='responsibility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
