# Generated by Django 3.2 on 2022-01-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_responsibility_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_doc',
            field=models.FileField(blank=True, default='CV/ImtiyazCV.pdf', null=True, upload_to='CV/'),
        ),
    ]
