# Generated by Django 3.2 on 2022-01-31 06:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blgoDetails',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
